# Generated by Django 3.0.6 on 2020-05-31 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6), size=None)),
            ],
        ),
    ]
